- name: SecEnhanced linux disabling and power cycle
  hosts: webservers
  sudo: True
  tasks:
    - name: Install required packages
      yum: name=python-selinux update_cache=yes

    - name: Disable SELinux
      selinux:  state=disabled

    - name: reboot host
      shell: sleep 10 && /sbin/shutdown -r now
      async: 300
      poll: 0
      become: true

    - name: waiting for server booting up
      local_action: wait_for
      args:
        host: ''
        port: 22
        delay: 30
        timeout: 600
        state: started
      become: false